import React,{useMemo,useState} from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Boxes, Plus, Search, Trash2 } from 'lucide-react';
import { db } from '../lib/db';
import { useAuth } from '../lib/AuthContext';
import { nowIso,uid,money,fmtDate,titleCase } from '../lib/utils';
import { saveRecord } from '../lib/cloudSync';
import type { TechnologyRecord } from '../types';
import { Button, Empty, Field, Modal, PageHeader, Select, StatusBadge, TextArea, TextInput } from '../components/UI';

const TYPES: TechnologyRecord['type'][]=['domain','dns_zone','certificate','public_ip','cloud_subscription','cloud_resource','database','api','integration','service_account','privileged_account','access_card','hardware_token','network_circuit','backup_job','storage_repository','website','source_repository','ci_cd','other'];
const STATUS: TechnologyRecord['status'][]=['active','inactive','planned','retiring','expired','unknown'];

export function TechnologyPage(){
  const{user}=useAuth();const orgId=user!.orgId;
  const rows=useLiveQuery(()=>db.technology.where('orgId').equals(orgId).toArray(),[orgId])||[];
  const sites=useLiveQuery(()=>db.sites.where('orgId').equals(orgId).toArray(),[orgId])||[];
  const[edit,setEdit]=useState<TechnologyRecord|null>(null);const[open,setOpen]=useState(false);const[q,setQ]=useState('');const[type,setType]=useState('');
  const filtered=useMemo(()=>rows.filter(r=>(!type||r.type===type)&&(!q||`${r.name} ${r.identifier} ${r.owner} ${r.vendor} ${r.urlOrAddress} ${r.accountOrTenant}`.toLowerCase().includes(q.toLowerCase()))),[rows,q,type]);
  return <><PageHeader title="Technology & Service Register" subtitle="Domains, certificates, cloud resources, databases, APIs, identities, circuits, repositories and specialist IT records that do not belong in the physical asset register." actions={<Button onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={16}/> Add record</Button>}/>
  <div className="toolbar"><label className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, ID, owner, vendor, address…"/></label><Select value={type} onChange={e=>setType(e.target.value)}><option value="">All record types</option>{TYPES.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</Select><span className="toolbar-count">{filtered.length} records</span></div>
  {!filtered.length?<Empty title="No matching technology records" text="Use this flexible register for cloud, domains, certificates, APIs, service accounts, circuits and any specialist technology that is not a physical asset."/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Technology / service</th><th>Owner / site</th><th>Security</th><th>Renewal / expiry</th><th>Cost</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><button className="table-link" onClick={()=>{setEdit(r);setOpen(true)}}><strong>{r.name}</strong><small>{titleCase(r.type)}{r.identifier?` • ${r.identifier}`:''}{r.urlOrAddress?` • ${r.urlOrAddress}`:''}</small></button></td><td><strong>{r.owner||'—'}</strong><small>{sites.find(s=>s.id===r.siteId)?.name||r.accountOrTenant||'—'}</small></td><td><span>{[r.mfa===true?'MFA':r.mfa===false?'No MFA':'',r.encryption===true?'Encrypted':r.encryption===false?'Not encrypted':'',r.internetExposed?'Internet exposed':''].filter(Boolean).join(' • ')||'Not recorded'}</span><small>{r.dataClassification||'—'}</small></td><td><span>{fmtDate(r.renewalDate||r.expiryDate)}</span><small>{r.expiryDate&&r.renewalDate?`Expiry ${fmtDate(r.expiryDate)}`:''}</small></td><td>{r.annualCost?money(r.annualCost,r.currency):r.monthlyCost?`${money(r.monthlyCost,r.currency)}/mo`:'—'}</td><td><StatusBadge status={r.status}/></td><td><button className="icon-btn danger" onClick={async()=>{if(confirm(`Delete ${r.name}?`))await db.technology.delete(r.id)}}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}
  {open&&<TechnologyForm record={edit} sites={sites} onClose={()=>setOpen(false)}/>}</>;
}

function TechnologyForm({record,sites,onClose}:{record:TechnologyRecord|null;sites:any[];onClose():void}){
  const{user}=useAuth();const exists=Boolean(record?.id);
  const[v,setV]=useState({siteId:record?.siteId||'',type:record?.type||'domain',name:record?.name||'',identifier:record?.identifier||'',owner:record?.owner||'',custodian:record?.custodian||'',vendor:record?.vendor||'',environment:record?.environment||'production',urlOrAddress:record?.urlOrAddress||'',accountOrTenant:record?.accountOrTenant||'',dataClassification:record?.dataClassification||'',businessCriticality:record?.businessCriticality||'medium',status:record?.status||'active',startDate:record?.startDate||'',expiryDate:record?.expiryDate||'',renewalDate:record?.renewalDate||'',monthlyCost:String(record?.monthlyCost??''),annualCost:String(record?.annualCost??''),currency:record?.currency||'AED',mfa:record?.mfa===undefined?'':String(record.mfa),sso:record?.sso===undefined?'':String(record.sso),encryption:record?.encryption===undefined?'':String(record.encryption),internetExposed:record?.internetExposed===undefined?'':String(record.internetExposed),backupProtected:record?.backupProtected===undefined?'':String(record.backupProtected),lastReviewedAt:record?.lastReviewedAt?.slice(0,10)||'',customData:record?.customData?Object.entries(record.customData).map(([k,val])=>`${k}=${val??''}`).join('\n'):'',notes:record?.notes||''});
  const n=(s:string)=>s?Number(s):undefined;const b=(s:string)=>s===''?undefined:s==='true';
  const parseCustom=(text:string)=>Object.fromEntries(text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf('=');return i<0?[line,'']:[line.slice(0,i).trim(),line.slice(i+1).trim()]}));
  return <Modal wide title={exists?'Edit technology / service':'Add technology / service'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const ts=nowIso();const row:TechnologyRecord={id:record?.id||uid(),orgId:user!.orgId,createdAt:record?.createdAt||ts,updatedAt:ts,createdBy:record?.createdBy||user!.id,updatedBy:user!.id,siteId:v.siteId||undefined,type:v.type as TechnologyRecord['type'],name:v.name.trim(),identifier:v.identifier,owner:v.owner,custodian:v.custodian,vendor:v.vendor,environment:v.environment as any,urlOrAddress:v.urlOrAddress,accountOrTenant:v.accountOrTenant,dataClassification:v.dataClassification,businessCriticality:v.businessCriticality as any,status:v.status as any,startDate:v.startDate,expiryDate:v.expiryDate,renewalDate:v.renewalDate,monthlyCost:n(v.monthlyCost),annualCost:n(v.annualCost),currency:v.currency,mfa:b(v.mfa),sso:b(v.sso),encryption:b(v.encryption),internetExposed:b(v.internetExposed),backupProtected:b(v.backupProtected),lastReviewedAt:v.lastReviewedAt,customData:parseCustom(v.customData),notes:v.notes};await saveRecord('technology',row);onClose()}}>
    <div className="section-title">Identity & ownership</div><div className="form-grid three"><Field label="Record type"><Select value={v.type} onChange={e=>setV({...v,type:e.target.value as any})}>{TYPES.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</Select></Field><Field label="Name"><TextInput required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></Field><Field label="Identifier / reference"><TextInput value={v.identifier} onChange={e=>setV({...v,identifier:e.target.value})}/></Field><Field label="Site"><Select value={v.siteId} onChange={e=>setV({...v,siteId:e.target.value})}><option value="">Enterprise / not site-specific</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field><Field label="Business owner"><TextInput value={v.owner} onChange={e=>setV({...v,owner:e.target.value})}/></Field><Field label="Technical custodian"><TextInput value={v.custodian} onChange={e=>setV({...v,custodian:e.target.value})}/></Field><Field label="Vendor / provider"><TextInput value={v.vendor} onChange={e=>setV({...v,vendor:e.target.value})}/></Field><Field label="Environment"><Select value={v.environment} onChange={e=>setV({...v,environment:e.target.value as any})}>{['production','dr','test','development','sandbox','other'].map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Account / tenant / subscription"><TextInput value={v.accountOrTenant} onChange={e=>setV({...v,accountOrTenant:e.target.value})}/></Field><Field label="URL / IP / address"><TextInput value={v.urlOrAddress} onChange={e=>setV({...v,urlOrAddress:e.target.value})}/></Field><Field label="Criticality"><Select value={v.businessCriticality} onChange={e=>setV({...v,businessCriticality:e.target.value as any})}>{['critical','high','medium','low'].map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Data classification"><TextInput value={v.dataClassification} onChange={e=>setV({...v,dataClassification:e.target.value})}/></Field></div>
    <div className="section-title">Security & resilience</div><div className="form-grid three">{[['MFA','mfa'],['SSO','sso'],['Encryption','encryption'],['Internet exposed','internetExposed'],['Backup protected','backupProtected']].map(([label,key])=><Field key={key} label={label}><Select value={(v as any)[key]} onChange={e=>setV({...v,[key]:e.target.value})}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></Select></Field>)}<Field label="Last reviewed"><TextInput type="date" value={v.lastReviewedAt} onChange={e=>setV({...v,lastReviewedAt:e.target.value})}/></Field></div>
    <div className="section-title">Lifecycle & commercial</div><div className="form-grid three"><Field label="Status"><Select value={v.status} onChange={e=>setV({...v,status:e.target.value as any})}>{STATUS.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Start date"><TextInput type="date" value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></Field><Field label="Expiry date"><TextInput type="date" value={v.expiryDate} onChange={e=>setV({...v,expiryDate:e.target.value})}/></Field><Field label="Renewal date"><TextInput type="date" value={v.renewalDate} onChange={e=>setV({...v,renewalDate:e.target.value})}/></Field><Field label="Monthly cost"><TextInput type="number" step="0.01" value={v.monthlyCost} onChange={e=>setV({...v,monthlyCost:e.target.value})}/></Field><Field label="Annual cost"><TextInput type="number" step="0.01" value={v.annualCost} onChange={e=>setV({...v,annualCost:e.target.value})}/></Field><Field label="Currency"><TextInput value={v.currency} onChange={e=>setV({...v,currency:e.target.value})}/></Field></div>
    <Field label="Custom fields (one key=value per line)" hint="Use this for record-specific information such as registrar, certificate thumbprint, Azure resource ID, database version, API authentication type or access-card number."><TextArea rows={5} value={v.customData} onChange={e=>setV({...v,customData:e.target.value})}/></Field><Field label="Notes"><TextArea value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></Field><div className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button>Save record</Button></div>
  </form></Modal>;
}
